import './globals.css'

import {  QueryClient, QueryClientProvider} from 'react-query'
import { ReactQueryDevtools } from 'react-query/devtools'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// Create a client
const queryClient = new QueryClient()

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      // Provide the client to your App
      <QueryClientProvider client={queryClient}>
      <body>{children}</body>
      <ReactQueryDevtools initialIsOpen={false} />
      </QueryClientProvider>
    </html>
  )
}
