'use client';
import './globals.css'
import {ThemeProvider} from './context/theme'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

    <ThemeProvider>
    <html lang="en">
      <body>{children}</body>
    </html>
    </ThemeProvider>
  )
}
